Fix: Ubersmith RWhois Server Parsing
blattersturm/WhoisParser pull request #2
Opened 2020-10-13 09:23 UTC by Fireant456

2020-10-13 13:29 UTC, technetium-cfx requested changes
Good find. What I still wonder though, is this whois server actually necessary? Querying ARIN using `n + x.x.x.x` does yield the correct information, as evident by the raw data. It just wasn't parsed correctly.

2020-10-13 13:29 UTC, technetium-cfx commented on Parser.php
> +            if (false !== strpos($this->rawdata,'Ubersmith RWhois Server')) {
This seems a bit odd to do. Shouldn't this happen in the postprocessor of the template?

2020-10-13 18:28 UTC, Fireant456 commented on Parser.php
> +            if (false !== strpos($this->rawdata,'Ubersmith RWhois Server')) {
the template is not used yet at this point. Templates are only used if a hostname matches the currently queried Whois server. This was added in the event that an exception that no template was found to look at the raw response of the Whois server to look for this specific header. Since I only have my host's domain name for their whois server, I wanted to resolve this template issue for anyone that has a host with this Whois server running.

2020-10-13 18:34 UTC, Fireant456 commented
@technetium-cfx In response to your first comment, it really depends on if every ARIN record gives a valid response in the eyes of Keymaster. If Keymaster is looking for valid parsing of the "contacts" then I believe that might work based on my host's ARIN records. But I am not sure if these are all filled in for all valid Whois records and not only found on the corresponding referral Whois server. You also do not get the most accurate information if you don't grab the response from the referral Whois server.

If Keymaster is doing any logging of this Whois data then it would probably be a detriment to remove the query to referrals servers. Since blattersturm made commits earlier that fixed the referral server queries I would assume that the might be necessary. Again I don't really have enough experience of Whois record responses to be certain.

2020-10-13 18:40 UTC, Fireant456 commented on Parser.php
> +            if (false !== strpos($this->rawdata,'Ubersmith RWhois Server')) {
Also ARIN is parsed correctly. The problem arises once the ARIN post processor tells the Parser to query the referral server that was declared in the ARIN response. Since the referral server for our affected IP address is not listed in the Config/whois.ini it will lead to the exception that a template could not be found and it will continue with the last used template assuming that a ARIN record would use a referral server following the ARIN format. Which as we have found is not the case in this instance.

2020-10-15 22:36 UTC, Fireant456 commented
I modified the PR to include more situations which have been found as a result of a couple more people reporting having resolution errors and providing the affected IP address. Made edits to the regex to match more custom formatting as discovered with the affected IP's responses as well as changed the header check to only look for the keyword "rwhois" in order to apply the Ubersmith template. So far all response examples I have found follow similar header and footer formats, so I believe the 3 tested IPs are all using Ubersmith. Only 1 response of the 3 did not explicitly say it was an Ubersmith server.

```php
$result = $Parser->lookup("173.231.61.179"); // RackNerd - WebNX
$result = $Parser->lookup("104.129.29.137"); // Sonoran - Quadranet
$result = $Parser->lookup("23.238.34.10"); // Hostwinds
```

2020-10-16 00:09 UTC, Fireant456 commented
Fixed Shaw Cable Provider IPs. They would refer to a rwhois server that required authentication. Could not find info on how to authenticate with this server and bypassed querying that particular rwhois server in favor of using the ARIN response data.

2020-10-16 07:09 UTC, merged